Repository openshift/dedicated-admin-operator, pull requests merged in 2019-06, with the labels that each got.

#49 SREP-1306 Add Alerts
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/40-dedicated-admin-operator-namespaces-rec-rule.PrometheusRule.yaml
  pkg/dedicatedadmin/dedicatedadmin.go
Labels: size/M

#51 Enable dedicated-admins to view Cluster Monitoring stack
  manifests/35-dedicated-admin-cluster-monitoring-view.ClusterRoleBinding.yaml
Labels: approved, lgtm, size/S

#52 SREP-1686 OLM bug when version hash starts with zero
  README.md
Labels: approved, lgtm, size/XS
