Repository openshift/dedicated-admin-operator, pull requests merged in 2019-08, with the labels that each got.

#68 SREP-1863: dedicated-admin systemgroup added to [cluster]rolebindings
  Gopkg.lock
  README.md
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admin.Namespace.yaml
  manifests/02-dedicated-admins-cluster.ClusterRoleBinding.yaml
  pkg/dedicatedadmin/project/resources.go
Labels: approved, lgtm, size/M

#69 Dedicated-admins can install operators from OperatorHub only
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
  manifests/07-dedicated-admins-operators.Role.yaml
  manifests/07-dedicated-admins-operators.RoleBinding.yaml
  manifests/08-dedicated-admins-marketplace.Role.yaml
  manifests/08-dedicated-admins-marketplace.RoleBinding.yaml
Labels: approved, lgtm, size/L

#70 Update RBAC so customer can install logging operator
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/05-dedicated-admins-logging.Role.yaml
  manifests/05-dedicated-admins-logging.RoleBinding.yaml
Labels: approved, lgtm, size/M

#71 Add RBAC so customer can manage CRs for CRDs installed by curated ope…
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
Labels: approved, lgtm, size/M

#72 Two minor fixes
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/02-dedicated-admins-cluster.ClusterRoleBinding.yaml
  manifests/06-dedicated-admins-logging.RoleBinding.yaml
Labels: approved, lgtm, size/XS

#73 Customer can get routes in all namespaces
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
Labels: approved, lgtm, size/XS

#74 Exclude openshift-logging namespace from cluster quota
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/04-openshift-logging.Namespace.yaml
Labels: approved, lgtm, size/XS
