Repository openshift/dedicated-admin-operator, pull requests merged in 2019-03, with the labels that each got.

#2 Lock Namespaces of objects defined in manifests/ folder
  manifests/01_operator_serviceaccount.yaml
  manifests/08_dedicated-cluster-admin_rolebinding.yaml
  manifests/14_operator_deployment.yaml
  manifests/16_operator_servicemonitor.yaml
Labels: size/XS

#3 SREP-905 Added Makefile to be used from ci-operator prow job
  Makefile
Labels: size/S

#6 Remove references to 'rogbas'
  build/build_and_push.sh
  cmd/manager/main.go
  pkg/controller/add_namespace.go
  pkg/controller/add_rolebinding.go
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/rolebinding/rolebinding_controller.go
  pkg/dedicatedadmin/dedicatedadmin.go
Labels: lgtm, size/S

#5 Revise permissions per SREP-1008
  build/build_and_push.sh
  manifests/00-openshift-dedicated-admin.Namespace.yaml
  manifests/01-dedicated-admin-operator.ServiceAccount.yaml
  manifests/02-dedicated-admins.Group.yaml
  manifests/03-dedicated-project-admin.ClusterRole.yaml
  manifests/03_dedicated-readers_group.yaml
  manifests/04-dedicated-cluster-admin.ClusterRole.yaml
  manifests/05-dedicated-admin-operator.ClusterRole.yaml
  manifests/06-prometheus-k8s.Role.yaml
  manifests/09_dedicated-cluster-reader_role.yaml
  manifests/10-dedicated-cluster-admin.CluterRoleBinding.yaml
  manifests/10_dedicated-cluster-reader_rolebinding.yaml
  manifests/11-dedicated-admin-operator-sa.RoleBindings.yaml
  manifests/11_dedicated-project-admin_role.yaml
  manifests/12-dedicated-admin-operator-sa.CluterRoleBindings.yaml
  manifests/13-prometheus-k8s.RoleBinding.yaml
  manifests/50-dedicated-admin-operator-config.ConfigMap.yaml
  manifests/51-dedicated-admin-operator.Deployment.yaml
  manifests/52-dedicated-admin-operator.Service.yaml
  manifests/53-dedicated-admin-operator.ServiceMonitor.yaml
  manifests/60-dedicated-admin-operator.ClusterOperator.yaml
  pkg/dedicatedadmin/rolebindings.go
Labels: lgtm, size/XL

#7 Change Dockerfile to a dual-staged build/run approach
  README.md
  build/Dockerfile
Labels: lgtm, size/S

#8 SREP-1037 Created a separate Dockerfile for ci-operator
  build/Dockerfile.ci-operator
Labels: size/S

#9 SREP-1037 Remove permission related clauses from Dockerfile for ci-oper
  build/Dockerfile.ci-operator
Labels: size/XS

#10 SREP-1037 Created CSV generator script
  scripts/gen_operator_csv.py
  scripts/templates/csv-template.yaml
Labels: size/L

#12 dedicated-project-admin can list the namespace
  manifests/03-dedicated-project-admin.ClusterRole.yaml
Labels: size/XS
