Repository openshift/dedicated-admin-operator, pull requests merged in 2019-10, with the labels that each got.

#79 dedicated-admins can create ClusterRoles
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
Labels: approved, lgtm, size/XS

#80 Moved logging configs to managed-cluster-config
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/04-openshift-logging.Namespace.yaml
  manifests/05-dedicated-admins-logging.Role.yaml
  manifests/06-dedicated-admins-logging.RoleBinding.yaml
Labels: approved, lgtm, size/L

#81 dedicated-admins can list, get, watch ClusterVersion CR
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
Labels: approved, lgtm, size/S

#83 Move CatalogSource to openshift-dedicated-admin
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/80-dedicated-admin-operator-registry.CatalogSource.yaml
  manifests/81-dedicated-admin-operator.Subscription.yaml
Labels: approved, lgtm, size/XS

#84 SREP-2178 Added perms for dedicated-admins to manage prometheus objects
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-project.ClusterRole.yaml
Labels: approved, lgtm, size/S

#85 SREP-2178 turn resources to plural in Role def
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-project.ClusterRole.yaml
Labels: approved, lgtm

#86 Added new black listed namespace to configs. Fix issue where rolebind…
  config/config.go
  pkg/controller/rolebinding/rolebinding_controller.go
Labels: approved, lgtm, size/S
