Repository openshift/dedicated-admin-operator, pull requests merged in 2019-04, with the labels that each got.

#14 SREP-1037 Move Dockerfile.ci-operator to a subfolder and renamed it
  build/ci-operator/Dockerfile
Labels: size/XS

#15 SREP-1037 Update image tag from build to builder
  build/ci-operator/Dockerfile
Labels: size/XS

#17 SREP-1037 Remove yum call from 2nd stage on Dockerfile
  build/ci-operator/Dockerfile
Labels: size/XS

#21 isclean make target is quiet unless it fails
  Makefile
Labels: approved, lgtm, size/S

#24 Fix ClusterRoleBindings for OLM
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
  manifests/00-dedicated-admins-project.ClusterRole.yaml
  manifests/00-dedicated-admins.Group.yaml
  manifests/02-dedicated-admin-operator-admin.ClusterRoleBinding.yaml
  manifests/02-dedicated-admin-operator-cluster.ClusterRoleBinding.yaml
  manifests/02-dedicated-admin-operator-project.ClusterRoleBinding.yaml
  manifests/02-dedicated-admins-cluster.ClusterRoleBinding.yaml
  manifests/10-dedicated-admin-operator.Role.yaml
  manifests/11-dedicated-admin-operator.RoleBinding.yaml
  manifests/14-prometheus-k8s.Role.yaml
  pkg/controller/operator/operator_controller.go
  pkg/controller/operator/operator_controller_test.go
  pkg/dedicatedadmin/operator/resources.go
Labels: approved, lgtm, size/L

#27 Add to env target: OPERATOR_IMAGE_URI
  Makefile
Labels: approved, lgtm, size/S

#29 Removed BUILD_DATE from version
  Makefile
Labels: approved, lgtm, size/XS

#31 Small fixes and additional namespaces blacklisted.
  Makefile
  manifests/10-dedicated-admin-operator.Deployment.yaml
  manifests/10-dedicated-admin-operator.Role.yaml
  pkg/dedicatedadmin/dedicatedadmin.go
Labels: approved, lgtm, size/S

#30 Break out common Make operations to standard.mk
  Makefile
  standard.mk
Labels: approved, size/L

#33 Change Dockerfile location to variable
  standard.mk
Labels: size/XS

#34 Unified Dockerfile in build/Dockerfile and updated README
  README.md
  build/Dockerfile
  standard.mk
Labels: approved, lgtm, size/S

#35 Remove build/ci-operator/Dockerfile
  build/ci-operator/Dockerfile
Labels: approved, size/S
