Repository openshift/dedicated-admin-operator, pull requests merged in 2019-07, with the labels that each got.

#53 Dedicated-admins can manage logging
  manifests/04-openshift-logging.Namespace.yaml
  manifests/05-dedicated-admins-logging.ClusterRole.yaml
  manifests/05-dedicated-admins-logging.RoleBinding.yaml
Labels: approved, lgtm, size/M

#54 Move blacklist regex to config and clean it up
  config/config.go
  pkg/controller/namespace/namespace_controller_test.go
  pkg/controller/rolebinding/rolebinding_controller_test.go
  pkg/dedicatedadmin/dedicatedadmin.go
Labels: approved, lgtm, size/XS

#55 Fix logging rolebinding
  manifests/05-dedicated-admins-logging.RoleBinding.yaml
Labels: approved, lgtm, size/XS

#56 Fixing rbac for logging and monitoring
  build/generate-operator-bundle.py
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/05-dedicated-admins-logging.Role.yaml
  manifests/06-dedicated-admins-logging.RoleBinding.yaml
  manifests/35-dedicated-admins-cluster-monitoring-view.RoleBinding.yaml
  manifests/36-dedicated-admins-cluster-monitoring-routes.Role.yaml
  manifests/37-dedicated-admins-cluster-monitoring-routes.RoleBinding.yaml
Labels: approved, lgtm, size/L

#58 Rework what is bundled in catalog vs in syncset
  .gitignore
  Makefile
  README.md
  build/check_pr.sh
  build/generate-operator-bundle.py
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
  manifests/00-dedicated-admins.Group.yaml
  manifests/10-dedicated-admin-operator.Role.yaml
  manifests/11-dedicated-admin-operator.RoleBinding.yaml
  manifests/30-dedicated-admin-operator.ClusterOperator.yaml
  manifests/35-dedicated-admins-cluster-monitoring-view.RoleBinding.yaml
  manifests/36-dedicated-admins-cluster-monitoring-routes.Role.yaml
  manifests/37-dedicated-admins-cluster-monitoring-routes.RoleBinding.yaml
  pkg/controller/add_operator.go
  pkg/controller/operator/operator_controller.go
  pkg/controller/operator/operator_controller_test.go
  pkg/dedicatedadmin/operator/resources.go
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
  scripts/templates/template.yaml
Labels: approved, lgtm, size/XXL

#59 Added CatalogSource and Subscription back into the template
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/80-dedicated-admin-operator-registry.CatalogSource.yaml
  manifests/81-dedicated-admin-operator.Subscription.yaml
  scripts/templates/template.yaml
Labels: approved, lgtm, size/M

#61 Customer can create verify tokens and access
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/00-dedicated-admins-cluster.ClusterRole.yaml
Labels: approved, lgtm, size/S

#60 Add missing OperatorGroup and fix operator permissions
  build/generate-operator-bundle.py
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/02-dedicated-admin-operator-cluster.ClusterRoleBinding.yaml
  manifests/02-dedicated-admin-operator.ClusterRole.yaml
  manifests/02-dedicated-admin-operator.ClusterRoleBinding.yaml
  manifests/02-dedicated-admin-operator.Role.yaml
  manifests/02-dedicated-admin-operator.RoleBinding.yaml
  manifests/82-dedicated-admin-operator.OperatorGroup.yaml
  scripts/generate_syncset.py
Labels: approved, lgtm, size/L

#62 Add reviewers to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#64 Add additional configmap verbs to operator
  manifests/02-dedicated-admin-operator.Role.yaml
Labels: approved, lgtm, size/XS

#63 Update version to pass build metadata with "+" separator
  standard.mk
Labels: approved, lgtm, size/XS

#65 Revert: Update version to pass build metadata with "+" separator
  standard.mk
Labels: approved, lgtm, size/XS

#66 Whitespace update to force build and new version to cleanup catalogso…
  README.md
Labels: approved, lgtm, size/XS

#67 Fix RBAC for operator's SA
  build/templates/olm-artifacts-template.yaml.tmpl
  manifests/02-dedicated-admin-operator.ClusterRoleBinding.yaml
  manifests/02-dedicated-admin-operator.ClusterRoleBindings.yaml
  manifests/02-dedicated-admin-operator.Role.yaml
  manifests/02-dedicated-admin-operator.RoleBinding.yaml
  scripts/generate_syncset.py
Labels: approved, lgtm, size/L
