Repository openshift/dedicated-admin-operator, pull requests merged in 2019-05, with the labels that each got.

#36 SREP-1268 Added supporting files to integrate ded-admin-operator into app-sre CI
  Makefile
  build/Dockerfile.catalog_registry
  build/check_pr.sh
  build/deploy.sh
  build/generate-operator-bundle.py
  build/templates/csv.yaml.tmpl
  build/templates/package.yaml.tmpl
  functions.mk
  project.mk
  standard.mk
Labels: lgtm, size/L

#37 SREP-1268 Added SSS template
  build/templates/olm-artifacts-template.yaml.tmpl
Labels: lgtm, size/M

#38 Add execute permission
  build/deploy.sh
Labels: approved, lgtm, size/XS

#39 Fix template indentation
  build/templates/olm-artifacts-template.yaml.tmpl
Labels: approved, lgtm, size/M

#40 SREP-1268 Adding missing steps to build/deploy.sh
  build/deploy.sh
  functions.mk
  standard.mk
Labels: lgtm, size/XS

#41 Correctly identify previous version
  functions.mk
Labels: lgtm, size/XS

#42 SREP-1268 Fix quay.io repo name for catalog img
  functions.mk
Labels: lgtm, size/S

#43 SREP-1268 Fix package name
  build/templates/package.yaml.tmpl
Labels: approved, lgtm, size/XS

#44 SREP-1268 Deploy Staging
  build/Dockerfile
Labels: lgtm, size/XS

#45 migrate saas repos to gitlab
  functions.mk
  standard.mk
Labels: approved, lgtm, size/S

#46 use the correct saas bundle repo
  standard.mk
Labels: approved, lgtm, size/XS

#47 Update yq image
  functions.mk
Labels: approved, lgtm, size/XS

#48 makefile typo
  functions.mk
Labels: approved, lgtm, size/XS
